server:
  port: 80
#  配置链路追踪
spring:
  zipkin:
    base-url: http://192.168.2.108:9411/
    sender:
      type: web
  #    配置跨域
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

#     网关路由规则
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: activity_route
          uri: lb://service-activity
          predicates:
            - Path=/admin/activity/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com