server:
  port: 7000
spring:
  zipkin:
    base-url: http://192.168.2.108:9411/
    sender:
      type: web
#      排除依赖
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration