server:
  port: 8002
spring:
  redis:
    host: 192.168.2.108
    password: 123456
  zipkin:
    base-url: http://192.168.2.108:9411/
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#自定义线程池配置
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300

#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"