server:
  port: 8000
spring:
  zipkin:
    base-url: http://192.168.2.108:9411/
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration